Fix setupJestCanvasMock type declaration
The declaration for setupJestCanvasMock included {}, so have changed to return type void instead.
This fixes error TS1183: An implementation cannot be declared in ambient contexts