Fix setupJestCanvasMock type declaration (#108)
* Fix setupJestCanvasMock type declaration

The declaration for setupJestCanvasMock included {}, so have changed to return type void instead.
This fixes error TS1183: An implementation cannot be declared in ambient contexts

* Add hrd543 to contributors

Following instructions in the contrbuting.md file, I have added myself to the contributors list

---------

Co-authored-by: hustcc <i@hust.cc>